### ISSUE TITLE
Building 1.6.0 for DSM 7.0/7.1 fails, textchat.h cannot be found

### ISSUE THREAD

**Issue by skaldenhoven** [meganz/MEGAcmd#787]
Since a couple of days the synology mega-cmd is not working on my NAS anymore. It starts the server and then crashes. Found the same happening to the Windows app but upgrading to 1.6.0 fixed this.
However as read in several threads the updated version is still 'dangling' somewhere at Synology. So I tried to compile it myself but getting the same error over and over again on different guest OS'es.

Ubuntu 16.04 won't let me setup the build environment so I abandoned that OS, even though it is mentioned in the README.md (which was last modified 2 years ago). Tried with the prereqs from the main page and also tried the prereqs from issue #777
```
root@ubuntu16:/toolkit# ./pkgscripts-ng/EnvDeploy -v 7.1 -p apollolake
[2023-03-15 10:42:06,313] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=base
Traceback (most recent call last):
  File "./pkgscripts-ng/EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "./pkgscripts-ng/EnvDeploy", line 69, in main
    toolkit.download(args.quiet)
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 192, in download
    self.__downloader.download_base_tarball(quiet)
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 90, in download_base_tarball
    quiet
  File "/toolkit/pkgscripts-ng/include/python/pkgdeploy.py", line 107, in _download
    data = json.loads(response.read())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Next tried Ubuntu 18.04/20.04 all with the same error.

```2246: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2255: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2264: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2273: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2282: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2289: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2299: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2309: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2319: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
2329: //source/MEGAcmd/MEGAcmd/sdk/sdk_build/install/include/mega/command.h:30:10: fatal error: textchat.h: No such file or directory
```

Have searched all places but no one with the same issue. I verified the textchat.h file exists in the include directory of the sdk source and it does.

```root@ubuntu18:/toolkit/source/MEGAcmd/MEGAcmd/sdk/include/mega# ls
account.h         db.h                  json.h                mega_http_parser.h       raid.h                       thread          waiter.h
attrmap.h         drivenotify.h         logging.h             mega_utf8proc.h          request.h                    thread.h        win32
autocomplete.h    fileattributefetch.h  mediafileattribute.h  mega_zxcvbn.h            rotativeperformancelogger.h  transfer.h      wincurl
backofftimer.h    filefingerprint.h     megaapp.h             node.h                   serialize64.h                transferslot.h  wp8
base64.h          file.h                mega_ccronexpr.h      nodemanager.h            setandelement.h              treeproc.h
command.h         filesystem.h          megaclient.h          osx                      share.h                      types.h
config-android.h  gfx                   mega_dict-src.h       pendingcontactrequest.h  sharenodekeys.h              useralerts.h
console.h         gfx.h                 mega_evt_queue.h      posix                    sync.h                       user.h
crypto            heartbeats.h          mega_evt_tls.h        proxy.h                  testhooks.h                  utils.h
db                http.h                mega_glob.h           pubkeyaction.h           textchat.h                   version.h```

My steps for building are as follows.
Prepare env.
```apt-get install git -y
mkdir -p /toolkit
cd /toolkit
git clone https://github.com/SynologyOpenSource/pkgscripts-ng
apt-get install cifs-utils \
    python \
    python3 \
    python3-pip
cd pkgscripts-ng
git checkout DSM7.1
./EnvDeploy -v 7.1 -p apollolake
```
Then to get the mega-cmd code and compile
```cd /root
git clone https://github.com/meganz/MEGAcmd.git
cd MEGAcmd && git submodule update --init --recursive
cd ..
cp -r MEGAcmd/build/SynologyNAS/toolkit /
cp -r /root/MEGAcmd /toolkit/source/MEGAcmd/
cd /toolkit
nano ./source/MEGAcmd/SynoBuildConf/depends (changed to 7.1)
nano ./source/MEGAcmd/INFO.sh (changed to 7.1)
./pkgscripts-ng/PkgCreate.py MEGAcmd
```

Buildlog also attached
[MEGAcmd.build.txt](https://github.com/meganz/MEGAcmd/files/10978256/MEGAcmd.build.txt)

Any hints would be very appreciated and of course as mentioned by others as well, perhaps Mega can provide the built binaries for Synology? Perhaps on request from support.
Or perhaps share if there are any other requirements to the building environment so we can build it ourselves?

**Comment by skaldenhoven** [comment]
Also tried Debian 9-10-11 with same result of not being able to find textchat.h.
Also downloaded the release files for 1.5.1 to make sure that I have all relevant files and not a breaking commit.

**Comment by polmr** [comment]
Newer releases of MEGAcmd for NAS (Synology/QNAP) featuring several improvements and fixes, can now be downloaded from here: https://mega.io/nas.

**Comment by skaldenhoven** [comment]
Does it need time to replicate at SYnology? Since current version is still 1.4.0 on their website.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/17336093/233921832-1ea7aafa-cc6c-40f0-8e9f-394bd9100e7c.png">

**Comment by polmr** [comment]
Synology/QNAP stores will no longer receive updates. From now on https://mega.io/nas would be the proper (and faster) way to get updated MEGAcmd packages. Apologies for the inconveniences.

**Comment by skaldenhoven** [comment]
> Synology/QNAP stores will no longer receive updates. From now on https://mega.io/nas would be the proper (and faster) way to get updated MEGAcmd packages. Apologies for the inconveniences.

That's no problem for me. More than happy to install package manually. So this is great news.
Only thing is on this page I cannot seem to find the new packages. I'm probably overlooking it. The link for Synology is still directing to Synology website.

![image](https://user-images.githubusercontent.com/17336093/233927812-a1d8a2b8-64d0-449f-b6d6-a451a4ae2a98.png)

**Comment by polmr** [comment]
Thanks @skaldenhoven , open the URL in an icognito browser, you shall see it updated

**Comment by polmr** [comment]
Thanks @skaldenhoven for reporting that , 
You are seing a cached version. Can you try to open it in a different browser, or a new separated incognito window?

**Comment by skaldenhoven** [comment]
Well the screenshot actually was an incognito browser already since I thought of that as well. (See upper right hand of screenshot where it states Incognito)
Perhaps localized (Dutch) version not updated yet, since when I switch to English it does show the correct link.
For now it works and I got the package. Probably still some syncing being done for the localized versions of your website.

**Comment by polmr** [comment]
Yes, @skaldenhoven . It will be fixed soon. Thanks again for your inputs and workaround!
