### ISSUE TITLE
Can not mega-login anymore

### ISSUE THREAD

**Issue by queuereactive** [meganz/MEGAcmd#832]
Hi,

 I got an issue which looks similar to one described here (https://github.com/meganz/MEGAcmd/issues/802)

> $ mega-login -vvvv $login $pwd
[API:debug: 05:23:14] actUponLogin login
[API:debug: 05:23:14] actUponLogin login email: $login
Enter the code generated by your authentication app:  123456
[API:verbose: 05:23:18]  Using confirmation pin: 123456
[API:debug: 05:23:19] actUponLogin login
[API:debug: 05:23:19] actUponLogin login email: $login
[API:debug: 05:23:19] Login correct ... $login
[debug: 05:23:19] Session file: /home/$login/.megaCmd/session
[debug: 05:23:19] Syncs file: /home/$login/.megaCmd/syncs
[debug: 05:23:19] Backups file: /home/$login/.megaCmd/backups
[debug: 05:23:19] Excluded file: /home/$login/.megaCmd/excluded
[debug: 05:23:19] Exclusion file: /home/$login/.megaCmd/excluded
[API:debug: 05:23:19] Excluded name: .*
[API:debug: 05:23:19] Excluded name: Thumbs.db
[API:debug: 05:23:19] Excluded name: desktop.ini
[API:debug: 05:23:19] Excluded name: ~*
[API:info: 05:23:19] Fetching nodes ...
Fetching nodes ||#####################################################################################||(291/291 MB: 100.00 %)

Nothing happens after "Fetching nodes" - it does not matter for how long to wait for it to finish - it is just stuck.

I tried several different ubuntu machines - the result is the same.
I tried to follow the steps mentioned here (https://github.com/meganz/MEGAcmd/issues/802#issuecomment-1502896832) but mega-cmd-server not crashing.

> Reading symbols from mega-cmd-server...
Reading symbols from /usr/lib/debug/.build-id/3e/407be036ee5dc86c2d181ffd717a51c2325095.debug...
(gdb) r
Starting program: /usr/bin/mega-cmd-server
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe7fff640 (LWP 1797709)]
[New Thread 0x7fffe77fe640 (LWP 1797710)]
[New Thread 0x7fffe6ffd640 (LWP 1797711)]
[New Thread 0x7fffe67fc640 (LWP 1797712)]
[New Thread 0x7fffe5ffb640 (LWP 1797713)]
[New Thread 0x7fffe57fa640 (LWP 1797714)]
[New Thread 0x7fffe4ff9640 (LWP 1797715)]
[New Thread 0x7fffdffff640 (LWP 1797716)]
[New Thread 0x7fffdf7fe640 (LWP 1797717)]
[New Thread 0x7fffdeffd640 (LWP 1797718)]
[New Thread 0x7fffde7fc640 (LWP 1797719)]
[New Thread 0x7fffddffb640 (LWP 1797720)]
[New Thread 0x7fffdd7fa640 (LWP 1797721)]
[New Thread 0x7fffdcff9640 (LWP 1797722)]
[New Thread 0x7fffcbfff640 (LWP 1797723)]
[New Thread 0x7fffcb7fe640 (LWP 1797724)]
[New Thread 0x7fffcaffd640 (LWP 1797725)]
[New Thread 0x7fffca7fc640 (LWP 1797726)]
...
[New Thread 0x7fffc9ffb640 (LWP 1797727)]
[New Thread 0x7fffc97fa640 (LWP 1797844)]
[API:err: 05:23:19] Unable to FileAccess::fopen('/home/$login/.megaCmd/megaclient_statecache12_status_ZFQ0SGRmTUxtLU3vmmfBqFgxBlwXY86c5v2a.db'): sysstat() failed: error code: 2: No such file or directory
[API:err: 05:23:19] Unable to FileAccess::fopen('/home/$login/.megaCmd/megaclient_statecache12_ZFQ0SGRmTUxtLU3vmmfBqFgxBlwXY86c5v2a.db'): sysstat() failed: error code: 2: No such file or directory
^C
Thread 1 "mega-cmd-server" received signal SIGINT, Interrupt.
0x00007ffff631b7ed in __GI___select (nfds=1024, readfds=0x555557cb1e88, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
69      ../sysdeps/unix/sysv/linux/select.c: No such file or directory.
(gdb)
quit
A debugging session is active.
        Inferior 1 [process 1797706] will be killed.
Quit anyway? (y or n) y

I guess the problem is somehow related to either to size of disk space allocated to my account or the number of files in there.

Alex

**Comment by queuereactive** [comment]
I managed to crash the server. Here is the output

> Thread 249 "mega-cmd-server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc9ffb640 (LWP 2168534)]
0x0000000000000000 in ?? ()
(gdb) set pagination off
(gdb) thread apply all bt

> Thread 249 (Thread 0x7fffc9ffb640 (LWP 2168534) "mega-cmd-server"):
#0  0x0000000000000000 in ?? ()
#1  0x00005555557041b8 in megacmd::MegaCMDLogger::log (this=0x5555579636f0, time=0x7fffc9ffab00 "12:46:37", loglevel=<optimized out>, source=0x7fffc9ffab20 "fs.cpp:332", message=0x7fff20000d80 "Async write finished OK") at src/megacmd
logger.cpp:266
#2  0x00005555557f8cb8 in std::function<void (char const*, int, char const*, char const*)>::operator()(char const*, int, char const*, char const*) const (__args#3=<optimized out>, __args#2=<optimized out>, __args#1=<optimized out>, __
args#0=<optimized out>, this=0x555557965e08) at /usr/include/c++/11/bits/std_function.h:590
#3  mega::ExternalLogger::log (this=0x5555573219c0 <mega::g_externalLogger>, time=0x7fffc9ffab00 "12:46:37", loglevel=5, source=0x7fffc9ffab20 "fs.cpp:332", message=0x7fff20000d80 "Async write finished OK") at src/logging.cpp:139
#4  0x00005555556dd700 in mega::SimpleLogger::~SimpleLogger (this=0x7fffc9ffa970, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:194
#5  0x00005555558dab68 in mega::PosixFileAccess::asyncopfinished (sigev_value=sigev_value@entry=...) at src/posix/fs.cpp:337
#6  0x00007ffff629edce in notify_func_wrapper (arg=0x7fffbc00d690) at ./rt/aio_notify.c:49
#7  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 248 (Thread 0x7ffff595d980 (LWP 2168533) "mega-cmd-server"):
#0  __libc_pread64 (offset=<optimized out>, count=8388608, buf=0x7fff19d47220, fd=103) at ../sysdeps/unix/sysv/linux/pread64.c:25
#1  __libc_pread64 (fd=fd@entry=103, buf=0x7fff19d47220, count=8388608, offset=8912896) at ../sysdeps/unix/sysv/linux/pread64.c:23
#2  0x00007ffff629e389 in handle_fildes_io (arg=<optimized out>) at ./rt/aio_misc.c:542
#3  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#4  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 21 (Thread 0x7fffc97fa640 (LWP 2164839) "mega-cmd-server"):
#0  0x00007ffff62e5868 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffc97f9800, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007ffff62ea6e7 in __GI___nanosleep (req=req@entry=0x7fffc97f9800, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00007ffff631c0df in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:31
#3  0x00005555556cc090 in megacmd::retryConnections (pointer=<optimized out>) at src/megacmd.cpp:4037
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 19 (Thread 0x7fffca7fc640 (LWP 2164837) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=70, readfds=0x555557ca7460, writefds=0x555557ca74e0, exceptfds=0x555557ca7560, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=0x555557ca7450) at src/posix/waiter.cpp:149
#2  0x00005555558b5530 in mega::MegaApiImpl::loop (this=0x555557c33df0) at src/megaapi_impl.cpp:6732
#3  0x00005555558b56c1 in mega::MegaApiImpl::threadEntryPoint (param=0x555557c33df0) at src/megaapi_impl.cpp:5523
#4  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 18 (Thread 0x7fffcaffd640 (LWP 2164836) "mega-cmd-server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555557ca8e28) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555557ca8e28) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555557ca8e28, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6293ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555557ca8dd8, cond=0x555557ca8e00) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555557ca8e00, mutex=0x555557ca8dd8) at ./nptl/pthread_cond_wait.c:627
#5  0x00005555557f007b in std::condition_variable::wait<mega::MegaClientAsyncQueue::asyncThreadLoop()::<lambda()> > (__p=..., __lock=..., this=0x555557ca8e00) at /usr/include/c++/11/condition_variable:103
#6  mega::MegaClientAsyncQueue::asyncThreadLoop (this=0x555557ca8dd0) at src/utils.cpp:2553
#7  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 17 (Thread 0x7fffcb7fe640 (LWP 2164835) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=68, readfds=0x555557ca7810, writefds=0x555557ca7890, exceptfds=0x555557ca7910, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=this@entry=0x555557ca7800) at src/posix/waiter.cpp:149
#2  0x00005555559ad985 in mega::GfxProc::loop (this=0x555557ca77f0) at src/gfx.cpp:114
#3  0x00005555559ae03d in mega::GfxProc::threadEntryPoint (param=<optimized out>) at src/gfx.cpp:104
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 16 (Thread 0x7fffcbfff640 (LWP 2164834) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=59, readfds=0x555557c296d0, writefds=0x555557c29750, exceptfds=0x555557c297d0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=0x555557c296c0) at src/posix/waiter.cpp:149
#2  0x00005555558b5530 in mega::MegaApiImpl::loop (this=0x555557bb6060) at src/megaapi_impl.cpp:6732
#3  0x00005555558b56c1 in mega::MegaApiImpl::threadEntryPoint (param=0x555557bb6060) at src/megaapi_impl.cpp:5523
#4  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 15 (Thread 0x7fffdcff9640 (LWP 2164833) "mega-cmd-server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555557c2b098) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555557c2b098) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555557c2b098, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6293ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555557c2b048, cond=0x555557c2b070) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555557c2b070, mutex=0x555557c2b048) at ./nptl/pthread_cond_wait.c:627
#5  0x00005555557f007b in std::condition_variable::wait<mega::MegaClientAsyncQueue::asyncThreadLoop()::<lambda()> > (__p=..., __lock=..., this=0x555557c2b070) at /usr/include/c++/11/condition_variable:103
#6  mega::MegaClientAsyncQueue::asyncThreadLoop (this=0x555557c2b040) at src/utils.cpp:2553
#7  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 14 (Thread 0x7fffdd7fa640 (LWP 2164832) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=57, readfds=0x555557c29a80, writefds=0x555557c29b00, exceptfds=0x555557c29b80, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=this@entry=0x555557c29a70) at src/posix/waiter.cpp:149
#2  0x00005555559ad985 in mega::GfxProc::loop (this=0x555557c29a60) at src/gfx.cpp:114
#3  0x00005555559ae03d in mega::GfxProc::threadEntryPoint (param=<optimized out>) at src/gfx.cpp:104
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 13 (Thread 0x7fffddffb640 (LWP 2164831) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=48, readfds=0x555557bab940, writefds=0x555557bab9c0, exceptfds=0x555557baba40, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=0x555557bab930) at src/posix/waiter.cpp:149
#2  0x00005555558b5530 in mega::MegaApiImpl::loop (this=0x555557b38320) at src/megaapi_impl.cpp:6732
#3  0x00005555558b56c1 in mega::MegaApiImpl::threadEntryPoint (param=0x555557b38320) at src/megaapi_impl.cpp:5523
#4  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 12 (Thread 0x7fffde7fc640 (LWP 2164830) "mega-cmd-server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555557bad308) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555557bad308) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555557bad308, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6293ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555557bad2b8, cond=0x555557bad2e0) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555557bad2e0, mutex=0x555557bad2b8) at ./nptl/pthread_cond_wait.c:627
#5  0x00005555557f007b in std::condition_variable::wait<mega::MegaClientAsyncQueue::asyncThreadLoop()::<lambda()> > (__p=..., __lock=..., this=0x555557bad2e0) at /usr/include/c++/11/condition_variable:103
#6  mega::MegaClientAsyncQueue::asyncThreadLoop (this=0x555557bad2b0) at src/utils.cpp:2553
#7  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 11 (Thread 0x7fffdeffd640 (LWP 2164829) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=46, readfds=0x555557babcf0, writefds=0x555557babd70, exceptfds=0x555557babdf0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=this@entry=0x555557babce0) at src/posix/waiter.cpp:149
#2  0x00005555559ad985 in mega::GfxProc::loop (this=0x555557babcd0) at src/gfx.cpp:114
#3  0x00005555559ae03d in mega::GfxProc::threadEntryPoint (param=<optimized out>) at src/gfx.cpp:104
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 10 (Thread 0x7fffdf7fe640 (LWP 2164828) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=37, readfds=0x555557b2dc00, writefds=0x555557b2dc80, exceptfds=0x555557b2dd00, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=0x555557b2dbf0) at src/posix/waiter.cpp:149
#2  0x00005555558b5530 in mega::MegaApiImpl::loop (this=0x555557aba5e0) at src/megaapi_impl.cpp:6732
#3  0x00005555558b56c1 in mega::MegaApiImpl::threadEntryPoint (param=0x555557aba5e0) at src/megaapi_impl.cpp:5523
#4  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 9 (Thread 0x7fffdffff640 (LWP 2164827) "mega-cmd-server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555557b2f5c8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555557b2f5c8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555557b2f5c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6293ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555557b2f578, cond=0x555557b2f5a0) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555557b2f5a0, mutex=0x555557b2f578) at ./nptl/pthread_cond_wait.c:627
#5  0x00005555557f007b in std::condition_variable::wait<mega::MegaClientAsyncQueue::asyncThreadLoop()::<lambda()> > (__p=..., __lock=..., this=0x555557b2f5a0) at /usr/include/c++/11/condition_variable:103
#6  mega::MegaClientAsyncQueue::asyncThreadLoop (this=0x555557b2f570) at src/utils.cpp:2553
#7  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 8 (Thread 0x7fffe4ff9640 (LWP 2164826) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=35, readfds=0x555557b2dfb0, writefds=0x555557b2e030, exceptfds=0x555557b2e0b0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=this@entry=0x555557b2dfa0) at src/posix/waiter.cpp:149
#2  0x00005555559ad985 in mega::GfxProc::loop (this=0x555557b2df90) at src/gfx.cpp:114
#3  0x00005555559ae03d in mega::GfxProc::threadEntryPoint (param=<optimized out>) at src/gfx.cpp:104
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 7 (Thread 0x7fffe57fa640 (LWP 2164825) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=26, readfds=0x555557aaff60, writefds=0x555557aaffe0, exceptfds=0x555557ab0060, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=0x555557aaff50) at src/posix/waiter.cpp:149
#2  0x00005555558b5530 in mega::MegaApiImpl::loop (this=0x555557a3ca20) at src/megaapi_impl.cpp:6732
#3  0x00005555558b56c1 in mega::MegaApiImpl::threadEntryPoint (param=0x555557a3ca20) at src/megaapi_impl.cpp:5523
#4  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 6 (Thread 0x7fffe5ffb640 (LWP 2164824) "mega-cmd-server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555557ab1888) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x555557ab1888) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555557ab1888, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6293ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x555557ab1838, cond=0x555557ab1860) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555557ab1860, mutex=0x555557ab1838) at ./nptl/pthread_cond_wait.c:627
#5  0x00005555557f007b in std::condition_variable::wait<mega::MegaClientAsyncQueue::asyncThreadLoop()::<lambda()> > (__p=..., __lock=..., this=0x555557ab1860) at /usr/include/c++/11/condition_variable:103
#6  mega::MegaClientAsyncQueue::asyncThreadLoop (this=0x555557ab1830) at src/utils.cpp:2553
#7  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 5 (Thread 0x7fffe67fc640 (LWP 2164823) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=24, readfds=0x555557ab0270, writefds=0x555557ab02f0, exceptfds=0x555557ab0370, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=this@entry=0x555557ab0260) at src/posix/waiter.cpp:149
#2  0x00005555559ad985 in mega::GfxProc::loop (this=0x555557ab0250) at src/gfx.cpp:114
#3  0x00005555559ae03d in mega::GfxProc::threadEntryPoint (param=<optimized out>) at src/gfx.cpp:104
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 4 (Thread 0x7fffe6ffd640 (LWP 2164822) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=110, readfds=0x555557964bd0, writefds=0x555557964c50, exceptfds=0x555557964cd0, timeout=0x7fffe6ffcaa0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=0x555557964bc0) at src/posix/waiter.cpp:149
#2  0x00005555558b5530 in mega::MegaApiImpl::loop (this=0x555557967800) at src/megaapi_impl.cpp:6732
#3  0x00005555558b56c1 in mega::MegaApiImpl::threadEntryPoint (param=0x555557967800) at src/megaapi_impl.cpp:5523
#4  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 3 (Thread 0x7fffe77fe640 (LWP 2164820) "mega-cmd-server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555579eb7d8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5555579eb7d8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5555579eb7d8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6293ac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555579eb788, cond=0x5555579eb7b0) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5555579eb7b0, mutex=0x5555579eb788) at ./nptl/pthread_cond_wait.c:627
#5  0x00005555557f007b in std::condition_variable::wait<mega::MegaClientAsyncQueue::asyncThreadLoop()::<lambda()> > (__p=..., __lock=..., this=0x5555579eb7b0) at /usr/include/c++/11/condition_variable:103
#6  mega::MegaClientAsyncQueue::asyncThreadLoop (this=0x5555579eb780) at src/utils.cpp:2553
#7  0x00007ffff66dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 2 (Thread 0x7fffe7fff640 (LWP 2164819) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=13, readfds=0x5555579ea730, writefds=0x5555579ea7b0, exceptfds=0x5555579ea830, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555558f0c35 in mega::PosixWaiter::wait (this=this@entry=0x5555579ea720) at src/posix/waiter.cpp:149
#2  0x00005555559ad985 in mega::GfxProc::loop (this=0x5555579ea710) at src/gfx.cpp:114
#3  0x00005555559ae03d in mega::GfxProc::threadEntryPoint (param=<optimized out>) at src/gfx.cpp:104
#4  0x00007ffff6294b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff6326a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

> Thread 1 (Thread 0x7ffff682d300 (LWP 2164813) "mega-cmd-server"):
#0  0x00007ffff631b7ed in __GI___select (nfds=1024, readfds=0x555557cb1ef8, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:69
#1  0x00005555557701b6 in megacmd::ComunicationsManagerFileSockets::waitForPetition (this=0x555557cb1e30) at src/comunicationsmanagerfilesockets.cpp:122
#2  0x00005555556d07b9 in megacmd::megacmd () at src/megacmd.cpp:4190
#3  0x00005555556b59e3 in main (argc=<optimized out>, argv=<optimized out>) at src/megacmd.cpp:5209
